AWSTemplateFormatVersion: '2010-09-09'
Description: Creates Lambda Functions to Provide Bus Tracker API
Resources:
  conversation:
    Properties:
      CodeUri: s3://mark-lambda-test-ul/00f4173086d9f98d653d7b5152d523d3
      Description: 'Provides responses for Lex '
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::086642646227:role/service-role/LambdaRole
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
  jsEndpoint:
    Properties:
      CodeUri: s3://mark-lambda-test-ul/1dad8e5f2c87abb3a3f4301ace8eca04
      Description: Web hook for bus bot
      Events:
        GetResource:
          Properties:
            Method: Post
            Path: /find
          Type: Api
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::086642646227:role/Run_Lex
      Runtime: nodejs6.10
      Timeout: 5
    Type: AWS::Serverless::Function
  routesFromStopDd:
    Properties:
      CodeUri: s3://mark-lambda-test-ul/15f6cd95ebcaf24ac25a5fb529b7a9b8
      Description: Returns Bus Times from Stop ID
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::086642646227:role/service-role/LambdaRole
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
  stopsNearLocation:
    Properties:
      CodeUri: s3://mark-lambda-test-ul/89a5f9e7ea5cbb5b6d77bcbbf716cf08
      Description: Find Bus Stops Given an address
      Environment:
        Variables:
          GOOGLE_MAPS_KEY: AIzaSyBm-fjV3flb-_BYwIzR5CwrcIHzbtxJgxc
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::086642646227:role/service-role/LambdaRole
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
